---
title: "Genómica_Poblacional"
author: "Jaqueline Flores"
date: "1/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("ggplot2")
# install.packages("readr")
# install.packages("dplyr")
# install.packages("tidyr")
# install.packages("cowplot")
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(cowplot)
```

```{r}
EU <- read_delim("EU.geno.ld", delim = "\t")
OC <- read_delim("OC.geno.ld", delim = "\t")
US <- read_delim("US.geno.ld", delim = "\t")

EU$dist <- ceiling((EU$POS2 - EU$POS1)/1000)*1000
OC$dist <- ceiling((OC$POS2 - OC$POS1)/1000)*1000
US$dist <- ceiling((US$POS2 - US$POS1)/1000)*1000

EU2 <- group_by(EU,dist) %>%
  summarise(meanR2 = mean(`R^2`))

OC2 <- group_by(OC,dist) %>%
  summarise(meanR2 = mean(`R^2`))
  
US2 <- group_by(US,dist) %>%
  summarise(meanR2 = mean(`R^2`))  

dd <- bind_rows(EU2,OC2,US2)

dd$pop <- rep(c("EU","OC","US"),c(nrow(EU2),nrow(OC2),nrow(US2))) 

write_csv(dd,"EU_OC_US.windowed.ld.csv")
```

```{r}
het <- read_delim("EU_OC_US.het",delim = "\t")
het
```

```{r}
het$Heterozygosity <- 1-(het$`O(HOM)`/het$N_SITES) 
het$Population <- c(rep("EU",3),rep("OC",3),rep("US",3))
A <- ggplot(het,aes(x = Population, y = Heterozygosity, col = Population)) + geom_point()+ theme_bw() + theme(legend.position = "none") + xlab("")
A
```

```{r}
pi_EU <- read_delim("EU.windowed.pi",delim = "\t")
pi_EU
```

```{r}
pi_OC <- read_delim("OC.windowed.pi",delim = "\t")
pi_OC
```

```{r}
pi_US <- read_delim("US.windowed.pi",delim = "\t")
pi_US
```

```{r}
pi_all <- bind_rows(pi_EU,pi_OC,pi_US)
pi_all$Population<-c(rep("EU",nrow(pi_EU)),rep("OC",nrow(pi_OC)),rep("US",nrow(pi_US)))

B <- ggplot(pi_all,aes(x = Population, y = PI, col = Population))+
      geom_jitter(col = "grey",width = 0.1)+ 
      geom_boxplot(notch = T, alpha = 0,outlier.shape = NA)+ 
      theme_bw()+
      theme(legend.position = "none")+
      xlab("")+
      ylab(expression(pi))
B
```

